### PR TITLE
Reflect WG independence in charter.

### PR DESCRIPTION
**Pull request by barath**
This PR addresses concerns regarding the current charter draft and aligns it with the [W3C Charter Template](https://w3c.github.io/charter-drafts/charter-template.html) and with 126 W3C WG charters both past and present that I reviewed whose language is akin to this PR, ensuring that the WG charter reflects the independence of the Solid WG.

### CODE REVIEW

**Review by acoburn — APPROVED** [review]
I agree. It is important to align the Solid WG charter text with the pattern found in other, existing working groups.

The background section already details the historical relationship between the Solid Protocol specification and the Solid Community group, and the scope section should, as per the [W3C template](https://w3c.github.io/charter-drafts/charter-template.html#scope), be brief.

**Review by justinwb — APPROVED** [review]
This looks reasonable to me 👍 

I hope and expect that we’ll receive valuable submissions to the working group from multiple avenues, including the CG.

**Comment by csarven** [comment]
>This PR addresses concerns

Where were these concerns raised? Are they documented and accessible to the CG?

---

Using the W3C Process as guidance, in particular [Reopening a Decision When Presented With New Information](https://www.w3.org/2023/Process-20230612/#WGChairReopen), there is neither new information here or sufficient deliberation by the CG.

The existing text incorporated an understanding and the needs expressed by a set of charters that's also shared by the Solid WG charter. This was discussed numerous times in CG meetings and PRs. It also draws from https://github.com/w3c/charter-drafts/issues/262 where there is work on improving the template to that end so that there is better guidance available to where it may be applicable to.

---

>I hope and expect that we’ll receive valuable submissions to the working group from multiple avenues, including the CG.

The original text addressed that adequately:

>The Working Group will not adopt new proposals until they have matured through the <a href="https://www.w3.org/groups/cg/solid">W3C Solid Community Group</a> or another similar incubation phase.

---

This PR was merged 28 minutes after it was created, without CG's consent.

The understanding in the CG has been that the group will advance issues/PRs to, and it would then be assigned to @pchampin (W3C) for merging. See for example: https://github.com/solid/specification/blob/main/meetings/2023-04-12.md#overview-of-todays-agenda and how the CG has been processing issues/PRs for the charter. This has served well for the group - working closely, in the open, with W3C staff - and has the additional benefit of any oversight, e.g.:

The proposed WG charter is still under horizontal review and making changes along the lines proposed in this PR without CG's consent is unacceptable behaviour.

The group is working under the assumption that all participants are aware of the rules and understand expected behaviors of open standards development, in addition to Solid CG's contributing guidelines, norms, and so forth. If there is unclarity or support is needed for better participation, everyone is welcome to reach out for guidance.

---

Reverting commit.

**Comment by woutermont** [comment]
The audacity 🤯  This is plainly a coordinated attempt of some people to ignore the community's input! It is blatantly **against the W3C's spirit of open standards!**

First of all, I second everything @csarven already pointed out. **There is a way concerns are raised, reflected upon, and worked through towards consensus**, and @barath, @acoburn and @justinwb know that all too well. 

Secondly, **there is nothing in the W3C charter template that warrants these changes to "align with"**. To the contrary, as @csarven pointed out, there is an ongoing effort at W3C to add the relation between CG and WG to the charter template; and this is nothing new. The W3C's [guide on Recommendation Track readiness](www.w3.org/Guide/standards-track), for example, gives precisely the text this PR removed as an example of how such relation could be expressed. Multiple WG charters already include it (e.g. [Web Platform WG](https://www.w3.org/2017/08/webplatform-charter.html), [Devices and Sensors WG](https://www.w3.org/2022/11/das-wg-charter.html), [MiniApps WG](https://www.w3.org/2021/01/miniapps-wg-charter.html)).

Similarly, the W3C's [guide on CG to WG transitions](https://www.w3.org/Guide/process/cg-transition.html) explicitly states that _"[t]he charter of the target Working Group should address ... [t]he nature of the working relationship between the Working Group and the Community Group (if any) for any deliverable originated by the Community Group."_ It also points out that the CG's consensus on the transition _"should include expectations about the working relationship with the Working Group moving forward."_ It is very clear that **the relationship between the Solid specification and the Solid CG is not "historical"**, as @acoburn claims it to be. The CG and WG each have their role to play, and while their work process can be largely independent, it is the CG that decides if and when a specification should transition.

I would be very interested in what other members of the community think about this, and what W3C staff have to say about such practices.

**Comment by melvincarvalho** [comment]
As the founder of the CG, my vision was for it to be an inclusive platform, accommodating both formal and casual initiatives. I recognize the WG's independence and its more formal nature, it's essential for it to chart its own path. The CG can then align itself accordingly, after the WG is formally approved.

**Comment by melvincarvalho** [comment]
> Reverting commit.

@csarven, I noticed the recent commit was reverted. It would be appreciated if, in the future, we could discuss changes to commits that have received multiple approvals. @barath put significant effort into this. Since we all share the goal of advancing the Solid working group to REC status, let's collaborate and ensure the group has the autonomy it needs. Thank you for understanding.

**Comment by csarven** [comment]
Indeed, agree to review a revision since it became apparent that the text might not be sufficiently clear for those outside of the CG, and W3C staff and well-versed AC representatives are already familiar with W3C charters, processes, and so forth, for whom the existing text is demonstrably clear.

---

To follow-up on the CG discussion and to triple clarify:

The Solid WG charter is proposed by the Solid CG, and so naturally changes require CG's approval.

The Solid Process / Editors Team (ET) says absolutely *nothing* about writing, updating, or approving charters (or anything remotely applicable) or bypassing the CG altogether for any matter whatsoever.

On a related note: W3C does say that (WG) chairs help develop charters with W3C staff contact. Nevertheless, the practice in W3C is still that participants/members of a group are involved, so it is not even the case with chairs running wild and making calls without checking with the rest of the group.

Doing this 28 minuter while we are in the middle of a horizontal review of the charter, without involving the CG, or the CG chair, or the W3C staff is unprofessional and problematic. Involving the group would have shown good faith and a shared understanding of our common goal.

---

Once this charter moves to the w3c/charter-drafts repo, we'll eliminate these kinds of shenanigans.

**Comment by melvincarvalho** [comment]
> we'll eliminate these kinds of shenanigans

@csarven  I understand the intent behind the statement, but I believe the use of the word 'shenanigans' might not convey the desired professionalism in this context.  IMHO, the charter reads better with the changes made and the effort that was put in by @barath and others.

**Pull request merged**
