### PR TITLE
clarify position wrt to other processes

### PR DESCRIPTION
**Pull request by pchampin**
address w3c/charter-drafts#459

### CODE REVIEW

**Review by csarven — COMMENTED** [review]
Of course it goes without saying when a deliverable (a CG's work item) is taken as a WG's ED or FPWD, and following REC, NOTE, REGISTRY.. requirements.

I would suggest to not introduce this text in the PR unless charter-drafts makes a similar recommendation that proposed charters should clarify the process that was used to produce the deliverables from an *incubation phase* ( https://www.w3.org/Guide/standards-track/ ) and that WG will use the W3C Process going forward. That's clearly not the case with the other charter proposals, so not sure why it needs to be called out for the Solid WG charter.

We are already in the process of updating the CG's EDs (and TRs) to not mention Solid Process (and thereby BDFL..), and probably cut CG-DRAFT/FINAL (as latest TR) any way.

I would not object to introducing this text if you (W3C Team) still wants to go ahead with it, but would you (W3C Team) at least consider removing this text once we (CG) update the TRs/EDs of the referenced deliverables to not mention Solid Process?

**Comment by melvincarvalho** [comment]
It’s prudent to maintain separation here; the dynamic nature and certain ambiguities within the CG charter, contrasted with the stability of the W3C process, warrant it.

**Review by acoburn — APPROVED** [review]
This is a good clarification given the current state of CG input documents. I probably wouldn't include the phrase "It goes without saying", since the text is literally saying just that.

**Comment by pchampin** [comment]
@csarven I would in general agree with your suggestion to not include this text, but some reviewers expressed concerns about that, hence this PR. I would keep the text even after the draft is updated and does not mention the Solid process.

@acoburn I included the text "It goes without saying" precisely to make it clear that we are not trying to introduce anything new or exceptional compared to other WGs. I would welcome suggestions for another wording, but I think we must emphasize the fact that this is "business as usual".

**Comment by csarven** [comment]
The mention of "Solid Process" was removed from the EDs of specifications by the following PRs:

* https://github.com/solid/specification/pull/585
* https://github.com/solid/web-access-control-spec/pull/124
* https://github.com/solid/solid-oidc/pull/224
* https://github.com/solid/notifications/pull/190
* https://github.com/solid/authorization-panel/pull/331
* https://github.com/solid/webid-profile/pull/108
* https://github.com/solid/type-indexes/pull/28

This topic was discussed in [2023-10-18 CG meeting](https://github.com/solid/specification/blob/main/meetings/2023-10-18.md#updating-solid-eds-sotd-to-remove-solid-process) and there were no objections to merge. It was also noted in the meeting updates to the EDs are "enough evidence" for @pchampin .

**Comment by pchampin** [comment]
I got multiple feedback, including from W3C staff, discouraging us to include this text in the charter, following the same rationale as @csarven above. Even more than the fact that "it goes without saying", the concern was that including it in one charter may give the impression that *other* charters may opt out of the W3C process.

I'm therefore closing this PR without merging it. The corresponding text will be instead included in the response sent to the AC reviewers with the new version of the charter, when finalized.

**Pull request closed without merging**
