### PR TITLE
Fix success criteria (testing, interop, horizontal review)

### PR DESCRIPTION
**Pull request by csarven**
See also https://github.com/solid/solid-wg-charter/issues/2

### CODE REVIEW

**Comment by pchampin** [comment]
Thanks for this. Any reason for not including the sentence about the TAG and https://www.w3.org/TR/design-principles/ ?

**Comment by csarven** [comment]
TAG is already covered in #coordination .

design-principles is under the purview of TAG.

design-principles is not explicitly called out in the template of w3c/charter-drafts (or other templates AFAIK).

**Review by pchampin — APPROVED** [review]
I think the second but sentence from 
  https://w3c.github.io/charter-drafts/charter-template.html#success-criteria
could be added, but generally OK with merging this.

**Comment by csarven** [comment]
Updated and approved as per https://github.com/solid/specification/blob/c63ef36dfab2eaf3a1e6de66a9cb90f184b33753/meetings/2023-03-29.md#fix-success-criteria-testing-interop-horizontal-review

**Pull request merged**
