### PR TITLE
Clarifies necessary coordination with W3C Groups that Solid Protocol reaches

### PR DESCRIPTION
**Pull request by csarven**

### CODE REVIEW

**Comment by pchampin** [comment]
Thanks for those suggestions. I agree that discussions with all of these groups make sense, but don't we run the risk to look to ambitious here?

**Comment by csarven** [comment]
It is an acknowledgement and intention to open communication lines. Also works in both directions, i.e., useful to signal to other Groups that they can reach out to the Solid WG because of shared interests or mutual understanding is necessary. Listing them here is not intended to require high bandwidth communication at all times. Some components/mechanisms in Solid may need to be taken by other Groups, or taken on by Solid. Approaching here with good faith so to not duplicate work or step on other Groups toes.

**Comment by elf-pavlik** [comment]
@pchampin are there any general guidelines available for which group to include and which not to include in this section?

**Review by elf-pavlik — APPROVED** [review]
If someone objects to a specific group they should still be able to submit a PR proposing removal.

**Review by elf-pavlik — APPROVED** [review]

**Pull request merged**
