### PR TITLE
Remove reference to Director

### PR DESCRIPTION
**Pull request by csarven**
As per https://www.w3.org/2023/Process-20230612/#dirfree-changes and upcoming https://github.com/w3c/charter-drafts/pull/424

### CODE REVIEW

**Review by woutermont — APPROVED** [review]
Seems in line with W3C decision. Let's hold off merging until https://github.com/w3c/charter-drafts/pull/424 actually goes through as well, or at the earliest 30-08-2023 (broad 5d from now).

**Comment by melvincarvalho** [comment]
@timbl's insights and expertise, honed over three decades of pioneering this work, are integral to Solid

**Comment by woutermont** [comment]
With all respect for @timbl, @melvincarvalho, this is a long-time coming, gradual [decision](https://www.w3.org/news/2023/w3c-updates-its-process-document/) made by the W3C in order to keep the consortium doing its good work when @timbl, like any person, decides to phase out and enjoy a well-deserved retirement. This is mostly an administrative procedure; I am sure @timbl will keep bugging us with his honed insights and expertise for years to come 😉  (No offense meant, of course, @timbl.)

**Comment by melvincarvalho** [comment]
@woutermont It might be prudent for him to approve this PR directly.

**Comment by oolivo** [comment]
Team, 

Tim is not retired. He's on vacation for 1 month. Along with most members of the CG. Because it's August. Frankly, the amount of major changes that have been made to the CG processes and structure this month (compared to the rest of the year), considering how much of the group is indisposed, is borderline inappropriate. 

Let's wait until the majority of the group, and in this case the individual being discussed, have actually returned before proposing more major changes to the CG. We can say it's been discussed in the public or that consensus has been reached, but that's false if the average attendance and activity is barely half of what it usually is. 

Is there some deadline or pressing reason that all these major changes need to be pushed through in August when most people are not around to opine? Ever since late July it's felt like we're rewriting major CG processes at a furious pace and I'm at a loss as to why the timing is such. And candidly, I've struggled to keep up myself due to August vacation schedules.

**Comment by woutermont** [comment]
@oolivo, why the elevated concern? No one says @timbl is retired, nor that this change should be rushed (my [initial reaction](https://github.com/solid/solid-wg-charter/pull/50#pullrequestreview-1594276908) indeed proposes the contrary), and it is assigned to @pchampin precisely to get the w#C's input. Let's give this change due process like anything else. 🙂 

---

Re attendance I must say that I do not feel much difference between the summer months and the rest of the year. At any given time, some people are harder to reach, but the overal attendance rate does not seem to vary much. So I would not let that impact the process too much.

**Comment by woutermont** [comment]
One thing I would add is that, apart from the W3C's general Director-free plan, for the Solid WG specifically it is probably also more desireable that an unelected legacy position of influence such as the directorship is not occupied by someone so closely linked to a single stakeholder in Solid (viz. @timbl being the CTO & Co-founder / Director of Inrupt).

**Comment by pchampin** [comment]
Everybody, breathe...

I just updated the title of this issue, to make it better reflect what this PR (just like w3c/charter-drafts/pull/424) is actually about.

It is a fact that, per Process 2023, the W3C does not have a Director anymore. Any reference to the Director in a future charter is therefore moot. In this light, this PR is appropriate (and actually required). I totally agree that we should wait for w3c/charter-drafts/pull/424 to be merged into the charter template before aligning to it, but I don't see why this would not happen shortly.

> @timbl's insights and expertise, honed over three decades of pioneering this work, are integral to Solid

There is no questioning that, but this is not the point here.

**Comment by csarven** [comment]
Oz, please note https://github.com/solid/specification/blob/main/CONTRIBUTING.md#contributions in particular guidance regarding claims.

You did not provide evidence to support your key claims. I took the liberty to publish some [Solid CG Meeting Data](https://github.com/solid/specification/discussions/564).

Your claims do not appear to be grounded on that data, and if anything, it shows the contrary. I'd like to invite you to consider verifying and correcting the data as needed.

Your claims are also not supported by the following, and again shows the contrary:
* [Code frequency over the history of solid/solid-wg-charter](https://github.com/solid/solid-wg-charter/graphs/code-frequency)
* [Contributors to solid/solid-wg-charter](https://github.com/solid/solid-wg-charter/graphs/contributors)

Additionally, while you are making the point that making a proposal through a PR is "hurried", I don't recall you making any statements along these lines when three individuals made changes to the WG charter without CG's consent, merging 28 minutes after its creation, which happened last week, i.e., in August!

>We're referencing an unmerged PR, and while the eagerness to comply is appreciated, this can wait until folks are back and the W3C actually updates their template in an official way.

The template in this case is not particularly significant. And as PAC mentioned:

> It is a fact that, per Process 2023, the W3C does not have a Director anymore. Any reference to the Director in a future charter is therefore moot.

Moreover, the following from the WG Charter as well as WG charter templates is in fact relevant:

>This charter has been created according to section 3.4 of the Process Document. In the event of a conflict between this document or the provisions of any charter and the W3C Process, the W3C Process shall take precedence.

Hence, even if "Director" remained in the text, it would be not be effective when any decision required the W3C Director.

Please let me know if any of the above is unclear.

**Comment by woutermont** [comment]
Thanks for the number crunching, @csarven; but please let us all follow @pchampin's advice:

> Everybody, breathe...

**Review by pchampin — APPROVED** [review]

**Review by elf-pavlik — APPROVED** [review]

**Pull request merged**
